### ISSUE TITLE
Remove imutils

### ISSUE THREAD

**Issue by ubamba98** [apurva1112/headpose#6]
Work can be done without it I think we do not need it @IAmSuyogJadhav/ @gktejus please see to it

**Comment by IAmSuyogJadhav** [comment]
It is there for a reason. I looked into the implementation of `imutils.VideoStream` and saw that it uses a multithreaded implementation of `cv2.videoCapture`. This causes `imutils.VideoStream` to run quite **_faster_** than the native `cv2.videoCapture`. That's why it's been included.
You can test this yourself.
